### ISSUE TITLE
Add CUDA Device Const CI Test

### ISSUE THREAD

**Issue by kab163** [LLNL/Umpire#960]
After https://github.com/LLNL/Umpire/pull/943, we realized we should add a similar test for cuda

Start with trying to add:
```
gcc_8_3_1_cuda_11_7_0:
  variables:
    SPEC: "+fortran +deviceconst +cuda tests=basic %gcc@=8.3.1 ^cuda@11.7.0+allow-unsupported-compilers"
    MODULE_LIST: "cuda/11.7.0"
  extends: .job_on_lassen
```
in the lassen jobs file
